name: Build Schemas
description: Gets new schemas from cluster
inputs:
  openshift_server_url:
    description: Openshift Server URL.
    required: true
  openshift_token:
    description: Openshift Bearer Token. Store in a secret.
    required: true
  name:
    description: Openshift Cluster identifier.
    default: ocp
runs:
  using: composite
  steps:
    - name: Authenticate and set context
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ inputs.openshift_server_url }}
        openshift_token: ${{ inputs.openshift_token }}
        insecure_skip_tls_verify: true
    - name: Update schemas
      shell: bash
      run: |
        pip install openapi2jsonschema
        cd $GITHUB_WORKSPACE
        python build_schema.py -u $(oc whoami --show-server) -t $(oc whoami -t) -s STRICT
    - name: Format artifact name
      shell: bash
      id: artifact
      run: |
        echo "::set-output name=name::artifact-$(oc version -o json | jq '.openshiftVersion')-${{ inputs.name }}"
    - name: Upload artifacts from generating schemas
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.artifact.outputs.name }}
        path: |
          schemas/
          skip_kinds.txt
        retention-days: 1
